$mod = SUPER

monitor = ,preferred,auto,1

# Keyboard
input {
  kb_layout = us,br
  kb_options = grp:win_space_toggle
}

# Noctalia
exec-once = noctalia --daemon

# Launcher
bind = SUPER, RETURN, exec, noctalia msg panel-toggle launcher

# Terminal
bind = $mod, T, exec, alacritty

# Fechar janela
bind = $mod, Q, killactive

# Print
bind = SUPER SHIFT, S, exec, sh -c 'f=$(mktemp --suffix=.png); grim -g "$(slurp)" "$f" && satty --filename "$f" --output-filename "$f" && wl-copy < "$f"; rm -f "$f"'

# Navegar entre janelas
bind = $mod, LEFT, movefocus, l
bind = $mod, RIGHT, movefocus, r
bind = $mod, UP, movefocus, u
bind = $mod, DOWN, movefocus, d

# Workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod CTRL, LEFT, workspace, e-1
bind = $mod CTRL, RIGHT, workspace, e+1

# Mover janela entre workspaces
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5

# Mover janelas
bind = $mod SHIFT, LEFT, movewindow, l
bind = $mod SHIFT, RIGHT, movewindow, r
bind = $mod SHIFT, UP, movewindow, u
bind = $mod SHIFT, DOWN, movewindow, d

# Mouse
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow
